// <auto-generated />
namespace Mod11_1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class v1_Addedrelatioship : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v1_Addedrelatioship));
        
        string IMigrationMetadata.Id
        {
            get { return "201604160942261_v1_Added-relatioship"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
